### PR TITLE
Book awesome page created by class

### PR DESCRIPTION
**Pull request by beyk**
In this project:
 * We  use JavaScript classes
 * We create class methods to add and remove books.
* implemented the CSS styles to match the wireframe design

### CODE REVIEW

**Comment by arslanbisharat** [comment]
Hi @beyk, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that is a collaborative project but both peers have not worked on the project as can be seen from commit history. 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by Zuhaib042 — COMMENTED** [review]
Hi @beyk @Sami-Ullah-Tufail 
While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that is a pair-programming session,
- [x] but @Sami-Ullah-Tufail  has not committed to this project. a commit to just add name in readme doesnt count a contribution.
- [x]  Also consider adding a descriptive PR summary. right now your PR summary is not descriptive. kindly elaborate in detail so that the reviewer knows, what changes are in this PR.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by sumairq — APPROVED** [review]
### Hi Team, 



Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
✔️ Good commit history
✔️Linters are passing
✔️Very professional README
✔️Correct Github flow
✔️Descriptive PR
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by Qoosim — COMMENTED** [review]
#  *Status: Invalid Request* :red_circle: 

Hi @beyk, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.



## Invalid Code Review Request

You have submitted a project, that 

- [x] that the linters tests are not running against the PR.
**NB** It is very wrong to be using the same PR for multiple milestones. Kindly create a new PR that will hold all the changes for this particular milestone and ensure it passes all the linters files.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by nicupop729 — COMMENTED** [review]
Hi @beyk and @Sami-Ullah-Tufail,

I need to let you know that @sumairq wrongly approved this PR for another milestone: **Awesome books: a complete website with navigation**.
Please take note that the approval for this milestone will be reverted in the dashboard.
After you fix the linter issues, you can further use this PR to ask for a review for **Awesome books: refactor to use JavaScript classes** milestone.

Remember that in order to have a review, you need to collaborate in pair-programming activities, the linters need to pass and you need to ask for a review for a milestone in accordance with what the feature branch holds.

When ready, you can ask for another review for *Awesome books: refactor to use JavaScript classes** milestone using this branch.

Thank you!

**Comment by enniopo** [comment]
Hi @beyk @Sami-Ullah-Tufail, the "Awesome books: a complete website with navigation" activity on your dashboard has been updated. When you are ready, please request another code review request. 
Apologies for any inconvenience caused.

**Pull request merged**
